--- # Endpoints configuration

/events:

  - path: /
    method: GET
    key_required: true
    admin_required: false
    token_required: false
    paternity: false
    sort:
      - date

  - path: /
    method: POST
    key_required: true
    admin_required: true
    token_required: true
    paternity: false
    upload:
      min: 1
      max: 1
      name: cover
      dest: ./uploads/events

  - path: /:id
    method: GET
    key_required: true
    admin_required: false
    token_required: false
    paternity: false

  - path: /:id
    method: PUT
    key_required: true
    admin_required: true
    token_required: true
    paternity: false
    upload:
      min: 1
      max: 1
      name: cover
      dest: ./uploads/events

  - path: /:id
    method: PATCH
    key_required: true
    admin_required: true
    token_required: true
    paternity: false
    upload:
      min: 0
      max: 1
      name: cover
      dest: ./uploads/events

  - path: /:id
    method: DELETE
    key_required: true
    admin_required: true
    token_required: true
    paternity: false


/alerts:

  - path: /
    method: GET
    key_required: true
    admin_required: false
    token_required: false
    paternity: false
    sort:
      - dateStart
      - dateEnd

  - path: /
    method: POST
    key_required: true
    admin_required: true
    token_required: true
    paternity: false

  - path: /:id
    method: GET
    key_required: true
    admin_required: false
    token_required: false
    paternity: false

  - path: /:id
    method: PUT
    key_required: true
    admin_required: true
    token_required: true
    paternity: false

  - path: /:id
    method: PATCH
    key_required: true
    admin_required: true
    token_required: true
    paternity: false

  - path: /:id
    method: DELETE
    key_required: true
    admin_required: true
    token_required: true
    paternity: false


/observations:

  - path: /
    method: GET
    key_required: true
    admin_required: false
    token_required: false
    paternity: false

  - path: /
    method: POST
    key_required: true
    admin_required: false
    token_required: true
    paternity: false
    upload:
      min: 1
      max: 3
      name: pictures
      dest: ./uploads/observations

  - path: /:id
    method: GET
    key_required: true
    admin_required: false
    token_required: false
    paternity: false

  - path: /:id
    method: DELETE
    key_required: true
    admin_required: false
    token_required: true
    paternity: true
