--- # Configuration of the resources models.


alerts:

  rois: { min: 1, max: 4 }


observations:

  position:
    lake: { min: 1, max: 4 }

  weather:
    sky: { min: 1, max: 6 }

  details:

    algae:
      extension: { min: 1, max: 3 }
      look: { min: 1, max: 4 }
      colour: { min: 1, max: 4 }

    foams:
      extension: { min: 1, max: 3 }
      look: { min: 1, max: 3 }
      height: { min: 1, max: 3 }

    oils:
      extension: { min: 1, max: 3 }
      type: { min: 1, max: 2 }

    litters:
      quantity: { min: 1, max: 3 }
      type: { min: 1, max: 10 }

    odours:
      intensity: { min: 1, max: 3 }
      origin: { min: 1, max: 6 }

    outlets:
      terminal: { min: 1, max: 2 }
      colour: { min: 1, max: 7 }
