openapi: 3.0.2

info:
  title: SIMILE API
  description: API description...
  version: 1.0.0
  license:
    name: GNU GPLv3
    url: https://choosealicense.com/licenses/gpl-3.0/
  contact:
    email: edoardo.pessina@polimi.it

tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers

servers:
  - url: "http://localhost:8000"
    description: Development server

security:
  - ApiKeyAuth: []
  - bearerAuth: []

paths:
  /surveys:
    $ref: "http://localhost:8000/docs/resources/surveys/surveys.yaml"

  /surveys/user/{user_id}:
    $ref: "surveys-by-user.yaml"

  /surveys/{survey_id}:
    $ref: "surveys-by-id.yaml"


components:

  securitySchemes:

    ApiKeyAuth:
      type: apiKey
      description: API key you have to insert in the header of each request. A key can be obtained through the website. It provides project authorization, not authentication.
      in: header
      name: X-API-KEY

    bearerAuth:
      type: http
      description: JWT generated by the server after a user successfully logs in. It can be omitted in some requests.
      scheme: bearer
      bearerFormat: JWT
