openapi: 3.0.2

info:
  title: SIMILE API
  description: API description...
  version: 1.0.0
  license:
    name: GNU GPLv3
    url: https://choosealicense.com/licenses/gpl-3.0/
  contact:
    email: edoardo.pessina@polimi.it

tags:
#  - name: admins
#    description: Secured Admin-only calls
#  - name: developers
#    description: Operations available to regular developers
  - name: Events
    description: "CRUD operations for management of events"

servers:
  - url: "http://localhost:8000"
    description: Development server

security:
  - ApiKeyAuth: []
  - bearerAuth: []

paths:

  /events:
    get:

      tags:
        - Events
      summary: "Retrieves all the events from the database"
      description: "Description..."
      operationId: get-events

      parameters:

        - name: includePast
          in: query
          description: "Include in the result also past events."
          required: false
          schema:
            type: boolean
            default: false

        - name: includeDeleted
          in: query
          description: "Include in the result also deleted events. Only **admin** users can set it to true."
          required: false
          schema:
            type: boolean
            default: false

        - name: orderByDate
          in: query
          description: "Order the results by date (descending)."
          required: false
          schema:
            type: boolean
            default: false



      responses:





components:

  securitySchemes:

    ApiKeyAuth:
      type: apiKey
      description: API key you have to insert in the header of each request. A key can be obtained through the website. It provides project authorization, not authentication.
      in: header
      name: X-API-KEY

    bearerAuth:
      type: http
      description: JWT generated by the server after a user successfully logs in. It can be omitted in some requests.
      scheme: bearer
      bearerFormat: JWT
