openapi: 3.0.0

#----------------------
# Metadata
#----------------------
info:
  title: "SIMILE Api"
  x-logo:
    url: "https://raw.githubusercontent.com/epessina/simile-app/master/docs/media/logo.png"
  description: "# Uno

    asdf

    # Overview

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

    ## Ciao

    asdfasdf

    # Test

    asdfsadf
  "
  contact:
    name: "Edoardo Pessina"
    email: "interreg-simile@polimi.it"
  license:
    name: "GNU GPLv3"
    url: "https://choosealicense.com/licenses/gpl-3.0/"
  version: "1.0.0"

#----------------------
# Server objects
#----------------------
servers:
  - url: "https://api-simile.como.polimi.it/v1"
    description: "Production server"

#----------------------
# Endpoints
#----------------------
paths: {}
